# Generated by Django 3.2.9 on 2021-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211209_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to=''),
        ),
    ]
