# Generated by Django 3.2.9 on 2021-12-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20211209_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='images/'),
        ),
    ]
