# Generated by Django 3.2.9 on 2021-12-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
