# Generated by Django 3.2.9 on 2021-12-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
